{{warning_banner}}

{% include "Containerfile.framework" %}

{% if type == "dev" or type == "standalone" %}
    {% include "Containerfile.mongodb" %}
{% endif %}

# Switch back to root to install system packages
USER root

{% if reverse_proxy == "caddy" %}
# Stage Reverse Proxy: Caddy
FROM mf-stack as rpmf-stack

# Install Caddy and create directories in one layer
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    gnupg \
    curl \
    debian-keyring \
    debian-archive-keyring \
    apt-transport-https && \
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && \
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends caddy && \
    mkdir -p /etc/caddy && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set permissions for non-root user
RUN chown -R ${USER}:${GROUP} /etc/caddy

# Copy files
COPY --chown=${USER}:${GROUP} --chmod=644 ./assets/Caddyfile /etc/caddy/Caddyfile
COPY --chown=${USER}:${GROUP} --chmod=640 ./assets/supervisor-caddy.conf /etc/supervisor/supervisor_config.d/3-supervisor-caddy.conf
{% endif %}

# Install Supervisor
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    supervisor && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create supervisor sub config and log directory and set permissions
RUN mkdir -p /etc/supervisor/supervisor_config.d /var/log/supervisor /run/supervisor && \
    chown -R ${USER}:${GROUP} /etc/supervisor /var/log/supervisor /run/supervisor

# Copy files
COPY --chown=${USER}:${GROUP} --chmod=644 ./assets/supervisord.conf /etc/supervisor/supervisord.conf

# Run the application with supervisor (all processes run as appuser)
ENTRYPOINT ["/usr/bin/supervisord"]
